### ISSUE TITLE
Extremely large applications and possibility of a store hierarchy

### ISSUE THREAD

**Issue by swalters** [zewa666/aurelia-store#10]
My concern is that extremely large applications such as mine would have so many registered actions that it would cause a performance hit.   Are there any plans to allow for a hierarchy of stores much like router/child routers? 

What's the advice for very large apps?

**Comment by zewa666** [comment]
I think your question contains actually two questions and I'll try to address both of them

1. Registering actions
When you register an action, all that happens is that it gets added to a map for identification purposes, so the overhead here would be pure memory consumption and performance of retrieving the searched action. Both things likely can be neglected as I don't see anything that soon enough could create troubles here.

2. Hierarchy / composed stores
What you're requesting here is essentially the classical Flux pattern, which works with multiple stores, thus multiple sub-states. While that opens up some flexibility, learnings over time have shown that you actually don't really get any benefit over it. The reason why Redux became so successful is because everything is in ONE SINGLE STATE. All the features like flexible middlewares, predictable state changes (you don't have to care about syncing the various stores) and integration into various plugins like DevTools, Timetraveling etc. Plus having one serialisable state allows you to easily keep track of snapshots.

Nevertheless nothing stops you from using multiple stores. They are just vanilla classes, which you can instantiate by yourself or use the Aurelia DI to create Transient stores. Its just that most of the times the conceived structuring plus is actually no benefit and introduces more complexity. I'd suggest reading up on differences between Flux/Redux and why a single state container approach is heavily favoured nowadays.

With regards to *lazy-loaded* actions. You control when actions are applied by calling store.registerAction. Thus if some of the actions are needed lets say only in a separate region of your application, then register them once you enter that part. The only thing that might could be added is a store.unregisterAction API in order to control proper removal.

Are there maybe any other use cases or things I haven't thought about that you're addressing?

**Comment by swalters** [comment]
@zewa666 Thanks for your time to answer so thoroughly.

The only other thing I see is if I did use multiple stores, how would global functions like
```
dispatchify(yourAction)("PARAM1", "MYPARAM2", "AND_SO_ON");
```
work?

I'm probably overthinking it.

**Comment by zewa666** [comment]
Thanks for asking, it is a certainly valid question.

With regards to dispatchify, this is another great example, why having one Store simplifies a lot of use cases. [Internally](https://github.com/zewa666/aurelia-store/blob/master/src/store.ts#L230) it does nothing more than obtaining the store instance via DI, which is easy as for the known type Store<T> there is only one registered Store present as singleton.

It would certainly be doable to create another HOC like dispatchify, where you'd provide the target store, but that would likely require your new stores to subclass the Base Aurelia Store.

Now back again to my initial points handling undo-redo accross multiple stores, keeping them in sync and maintaing there order really gets ugly and unpredictable really fast.

**Comment by zewa666** [comment]
I'm closing this one for know since there doesn't seem to be any immediately needed action. Lets reopen if that changes
