### ISSUE TITLE
The connectTo decorator doesn't work when using canActivate

### ISSUE THREAD

**Issue by Vheissu** [zewa666/aurelia-store#20]
One of my use cases is needing to check if a view-model can instantiate by checking if a project exists. Basically, I have a bunch of projects and you can view a singular project. 

This is what it looks like.

```
    async canActivate(params) {
        await this.store.dispatch(getCategories);
        await this.store.dispatch(loadProjects);

        const project: any = this.state.projects.reduce((project, currentItem) => {
            if (currentItem.slug === params.slug) {
                project = currentItem;
            }

            return project;
        }, {});

        if (!project.slug) {
            return new Redirect('');
        }

        this.project = project;
        this.projectAdded = new Date(project.added).toDateString();
    }
```

If I use `connectTo` on the class, it applies the state too late to the view-model. However, if I manually add the subscriber from inside of the `constructor` it allows me to do this check.

```
        this.store.state.subscribe(
            (state: State) => this.state = state
        );
```

The question here is: am I doing something wrong in my workflow or is the `connectTo` decorator the incorrect thing to use in this situation?

**Comment by zewa666** [comment]
connectTo will setup inside the bind hook. So it seems canActivate is running before that. Hm exactly these types of problems i've feared will happen with lifecycle overloading. What would be the very first hook to use?

**Comment by kennyfowler** [comment]
getting the right solution might be more tricky, because custom elements dont have the same lifecycle events as views. I didnt check it now, but i think bind is the first common event...

...i didnt notice this yet, because i usually inject the store in views manually, so i can subscribe with a function to spy on changes in the state.

**Comment by kennyfowler** [comment]
sorry, "created" is the first common hook, comes from "aurelia-templating".

**Comment by zewa666** [comment]
Right that was my thinking as well, the only generic part would be bind/unbind for all of them. Given that canActivate is likely either Router or Dialog related I think in that case one should prefer a normal subscription.

What would be possible is to let the user define the hooks for setup and teardown, but honestly this way the complexity of connectTo increases so much, that it's really not worth anymore to cary that cognitive load.

**Comment by obedm503** [comment]
@zewa666 that's where the [`connect` factory](https://github.com/zewa666/aurelia-store/issues/5#issuecomment-355777858) comes in

**Comment by zewa666** [comment]
yeah either that or passed in as an additional option to connectTo

**Comment by zewa666** [comment]
@Vheissu, @kennyfowler, @obedm503 what do you guys think about the following options for the decorator?

```typescript
export interface ConnectToSettings<T> {
  selector: (store: Store<T>) => Observable<T>;
  target?: string;
  setup?: string;
  teardown?: string;
}
```

- is `setup` and `teardown` descriptive enough?
- fine with keeping `bind` and `unbind` as default values?
- should the values be limited only to the available lifecycle hooks?

With regards to the last I'd say let it be open so even alternative use-cases for like patching other methods can be supported.

@Vheissu your example thus would look like:
```
connectTo<State>({
  selector: (store) => store.state,
  setup: "canActivate"
})
class YourVM
```

**Comment by kennyfowler** [comment]
**Naming**
I wouldnt bother going with setup and teardown; the only alternative that came up was: "i subscribe ON bind/attached/...." so "on" and "off", but i dont know if its misleading to register an event handler...

**Additional idea**
If you think about refactoring the decoarater, how about a fifth parameter for providing a function-name (a function from the class that subscribes to the store)

Finally i thought again about Vheissus problem: if im right, if canActivates return false, non of the other lifecyle methods will be called, so if you subscribe on canActivate and then return false, unsubscribe will never be called...

**Comment by Vheissu** [comment]
@zewa666 If the work wasn't too much, I think having the ability to specify your subscribe/unsubscribe methods for these situations like `canActivate` is a great idea. If the work is too involved, just documenting this caveat in the plugin documentation would still be enough, as manually subscribing isn't that big of a deal for me to be honest.

**Comment by zewa666** [comment]
@kennyfowler well grammar wise we could also say `subscribe to` and `unsubscribe from` but I guess setup/teardown pretty much expresses the intention on a general level.

With regards to the additional idea. Are you talking about the selector property and making it accept besides a selector function a string pointing to another function to do it?

Regarding @Vheissu's problem, I'm not sure its really an issue, since he'd use `setup` and would just have to dispose the subscription manually in his code before returning. This can be done by accessing the semi-private `_stateSubscription` property attached to the class by the decorator.
But it's definitely something worth an extra note in the documentation.

**Comment by kennyfowler** [comment]
@zewa666 
> With regards to the additional idea. Are you talking about the selector property and making it accept besides a selector function a string pointing to another function to do it?

no no, i'm talking about providing a name of a custom function from the decorated class, that is called with the new state. its often not enough to simply bind the state properties in the template, i often need to check if something in the state changed and then open or close  a dialog. i then need to inject and subscribe to the store manually.

```
export class Text {

    private stateChanged = (state: State): void => {
		if( /* condition to open the dialog */ ) {
			this.openComponentEditorDialog();
		} else if( /* condition to close the dialog */) {
			this.closeComponentEditorDialog();
		}
		this.state = state;
    }
    
    public bind(): void {
        this.store.state.subscribe(this.stateChanged);
    }
}
```
if i could provide the name of the callback to the decorater, i would not need to inject the store, subscribe and unsubscribe manually.

```
// view model
@connectTo({
  callback: 'stateChanged'
})

// decorator
this._stateSubscription = source.subscribe(state => {
    if (typeof settings === "object" && settings.callback) {
        this[settings.callback](state)
    }

    if (typeof settings === "object" && settings.target) {
        this[settings.target] = state;
    } else {
        this.state = state;
    }
});
```

**Comment by zewa666** [comment]
Thats pretty much what the selector property would be doing except that it should also accept a string pointing to a function vs only taking a function. I'm gonna create a new branch with the discussed changes here so its gonna be easier to review.

**Comment by zewa666** [comment]
@kennyfowler ok scratch what I said, now after properly reading through your issue I get what you meant. I've called the callback `onChanged` and it only accepts a string of a function which will be called and will receive the new state. If you take a look at this [commit](https://github.com/zewa666/aurelia-store/commit/d648391380106c99a96d0c3f6251a40fd29725ef) you'll see the new API.

If that's it I think we're pretty good for merging this. I think that should enable @Vheissu's use case and more

**Comment by kennyfowler** [comment]
@zewa666 cant test this right now, but just from code review, i think there are two issues:

* the new state is applied to the class property before the e.g. stateChanged is called, so a comparison between old state and new state isnt possible anymore.

so calling `this[settings.target](state)` before would solve this.

alternative (but this is really nitpicking): how about just using the target parameter?
```
if(this[settings.target] === "function") {
  this[settings.target](state);
} else {
  this[settings.target] = state;
}
```
this feels like i have full control, and i could even make the callback async, but i cant give you am example why i would do that. disadvantage: i'm responsible for updating `this.state`, but could also be an advantage...
```
async stateChanged(newState): Promise<void> {
   await something();

  this.state = newState;
}
```

* and there could be a second issue with `if (!this.hasOwnProperty(settings.onChanged))`, i'm not sure, i have to verify this myself, but i remember that we had problems with hasOwnProperty because of using typescript, if i'm right, typescript compiles class methods to prototype functions, and `this.hasOwnProperty` does not check on prototype... i will check this asap.

thx!

**Comment by zewa666** [comment]
Moving the call upfront makes sense. Regarding later that would Introduce sideffects which negate what the subscription is doing so im less of a fan of that. Whenever you've time give it a try. Don't wanna haste things here ;)

**Comment by zewa666** [comment]
You were right with both concerns, I totally forgot that hasOwnProperty will actually not check the prototype, which is the usual thing you want, but exactly not this time :) So a `handler in this` check fixes it. This is not related to TypeScript per se but generally a JavaScript thingy.
I've also moved the onChanged call up before the assignment so that you really can access both the previous and current state.

**Comment by zewa666** [comment]
@Vheissu, @kennyfowler merged this, I think we're in a good enough state. I'll close this one as it's getting pretty much off the original topic. Please open another issue if there are any additional implementation discussions necessary.
