### ISSUE TITLE
State subscription via decorator

### ISSUE THREAD

**Issue by zewa666** [zewa666/aurelia-store#5]
Provide means to hide RxJS details for the state subscription for those who favour more convention over configuration

**Comment by obedm503** [comment]
what about a `connect` factory function that returns a decorator that handles subscribing and unsubscribing, and mapping state to the instance using (reselect?) selectors? something like:
```ts
import { createConnect } from 'aurelia-store';

// connects in attached and disconnects in detached
export const connectAttached = createConnect('attached', 'detached');
// connects in activate and disconnects in deactivate
export const connectActivate = createConnect('activate', 'deactivate');
```
then
```ts
import { autoinject } from 'aurelia-framework';
import { Store } from 'aurelia-store';
import { connectActivate } from './connect';

@autoinject
// map state to props
@connectActivate(state => ({ count: state.count }))
export class App {
  count: number = 0;
  constructor(private store: Store){}
}
```
I've been using this pattern using a custom store also based on rxjs

**Comment by zewa666** [comment]
I personally would have favoured a prop decorator but a class based is fine as well. Tying it to lifecycle hooks could be too late though. The thing thats puzzling me though is how to get access to instance vars? Do you have a sample or could you provide a small PR showing how you intended to implement it?

**Comment by obedm503** [comment]
https://github.com/ncai-developers/studentaccess/blob/801b4000ce252e08c8a5913d6b51fccc22911a5b/src/store/index.ts

this uses [rstate](https://github.com/obedm503/rstate), what was meant to be a framework-independent state container. but after some time using it, I realized that it wasn't reaaaally the best way to do things, but some good patterns came out of using it, like the decorator factory. in short it was just an experiment.

rstate, relied on the redux-style [`createStore`](https://github.com/ncai-developers/studentaccess/blob/801b4000ce252e08c8a5913d6b51fccc22911a5b/src/store/create-connect.ts) factory instead of dependency injection, and passed that as the first argument to `createConnect`. I guess the same could be achieved using `aurelia.container.get(Store)` to get the instance either inside our outside `createConnect`.

in rstate, the created decorators, as used [here](https://github.com/ncai-developers/studentaccess/blob/801b4000ce252e08c8a5913d6b51fccc22911a5b/src/pages/profile/profile.ts), took a `mapStateToProperties` and a `mapDispatchToProperties` in react-redux fashion

also, the created function from `createConnect` could be used both as a decorator outside the class or a function inside the class instance. but i'm still not sure if this is a good idea

**Comment by zewa666** [comment]
Some very good ideas here. Need to play around with it a bit

**Comment by zewa666** [comment]
So I played around with it for a bit but didn't find any suitable solution.

What I would be looking for is something like this:

```
class Foo {
  @connectTo((store) => store.state) theState
}
```

The issue though happening here is that, what I meant with obtaining the instance, there isn't really a chance to get hold of the property `theState` since decorators only operate on static level during class declaration.

As such the alternative would be to provide a helper function using a callback as selector:

```
import { connectTo } from 'aurelia-store'

class Foo {
  theState;

  constructor() {
    connectTo(this.theState, (store) => store.state);
  }
}
```

any other ideas @obedm503 ?

**Comment by obedm503** [comment]
>class Foo {
>  @connectTo((store) => store.state) theState
>}
so, how would it work if i want to connect different properties to different parts of the state using something like `reselect`? would that result in multiple subscription to the `state`  observable? 
if so, this is what I was trying to avoid, that's why I ended up using `Object.assign` to "inject" the properties into the what ever instance the selectors where used on

>From what I get you've overriden the lifecycle hooks to make that happen, which is a really cool idea, but I fear it would interfer with existing implementations, base classes etc.

yeah, I don't know how well it would work with base classes, but it's the best I could come up with to handle "automatic" subscription and subscription to the `state`

**Comment by zewa666** [comment]
> so, how would it work if i want to connect different properties to different parts of the state using something like reselect?

Well you can use rxjs pluck for that.

```
var source = store.state.pluck('WHATEVER');
```

Reselect isn't really needed once you use RxJS as it provides all the tools out of the box, although nothing hinders you in doing so

**Comment by obedm503** [comment]
yes, I agree that `reselect` isn't necessary but still
>would that result in multiple subscription to the state observable?

**Comment by zewa666** [comment]
Yes it would, allthough reselect would be recalculated as well on the next state propagation. Depending on the use case you could add take(1) to immediately dispose the subscription after the first state.

**Comment by zewa666** [comment]
Here is another nice approach ditching reselect by using pure rxjs https://github.com/reactjs/reselect/issues/54

**Comment by zewa666** [comment]
@obedm503 so I ended up experimenting more and came pretty much to the same conclusion like you. There really isn't a nice way without overriding lifecycle methods. What I dislike with this is that you have a quite ugly path for TypeScript users as *injected* props and methods are not typesafe anymore.

Would you mind giving [this decorator implementation](https://github.com/zewa666/aurelia-store/blob/using-decorators/src/decorator.ts) a look and follow along [these testcases](https://github.com/zewa666/aurelia-store/blob/using-decorators/test/unit/decorator.spec.ts) for the usage?

**Comment by obedm503** [comment]
cool! 2 things:
- I would have used a  scoped variable instead of `_stateSubscription` pseudo private property to hold the subscription. the downside is that it's not testable if it's private
- I don't know if this would help with the typing problem, but can't you return the target cast as different type?
```ts
type StoreConsumer<T> = {
  state: Store<T>
}

export function connectTo<T>(settings?: (store: Store<T>) => Observable<T>) {
  // ...
  return function (target: any) {
    // ...
    return (target as type extends StoreConsumer<T>);
  }
}
```
ps: didn't actually test if this compiles

**Comment by zewa666** [comment]
thanks for the feedback.

1. I thought so as well, but then again as you stated testing becomes a lot harder. Not only that, there might also be a reason someone would like to unsubscribe earlier than unbind, for whatever reason. So hiding the subscription feels a bit dangerous.
2. well that would be possible but in that case you'd tie the decorator to a specific consumer, which doesn't scale well. I also thought about interfaces, but then again this doesn't feel very natural to the current Aurelia flow and besides that the optional flag you'd have to place would result in further issues.

**Comment by zewa666** [comment]
Alright I think we're good enough here, I've added additionally the option to override the target property, so it should be fine to start with. We'll see whether more requests are coming. Closing this for now. Thanks for the help @obedm503
